### ISSUE TITLE
Can you please upgrade this wrapper to use latest i18next version?

### ISSUE THREAD

**Issue by bhaskerchari** [leMaik/i18next-ko#2]
Hi,

Can you please upgrade this knockout wrapper to use latest i18next library since this is no more compatible with the latest version?

I don't think it makes proper sense still refer to the older versions of i18n as there has been lot of new advanced support added in the recent versions.

Thanks In Advance,
Bhasker

**Comment by leMaik** [comment]
I don't use this wrapper anymore, but I'd be happy to receive pull
requests. :-)

**Comment by xtr0** [comment]
PR #3

**Comment by leMaik** [comment]
Resolved by #3. Thank you very much for your PR! :+1:
