### ISSUE TITLE
Can't use dot in key

### ISSUE THREAD

**Issue by yydmay** [leMaik/i18next-ko#6]
My translation key looks like 'a.b.c.d'. It doesn't translate properly, it always show 'translation:a.b.c.d', tried debug it and see a 'keySeparator' property in getResource and addResource functions and it defaults to '.' is there a way to pass a parameter in to change default separator to something else?

Thanks

**Comment by leMaik** [comment]
Dots _can_ be used in keys, but your resourceStore must be a nested object.

E.g. if your key is `foo.bar`, your resource store should look like this:

```js
{
  foo:  {
    bar: 'buzz'
  }
}
```
