### ISSUE TITLE
Replace setLng with changeLanguage

### ISSUE THREAD

**Issue by chrswk** [leMaik/i18next-ko#7]
Hi

The method `setLng` from i18next was deprecated (and now removed with the latest 8.x releases). `changeLanguage` was added pretty long time ago, so I think most users should be fine. Other than that, no complaints, great library.

-Chris

**Comment by leMaik** [comment]
Good point, want to submit a PR? :+1:

**Comment by chrswk** [comment]
Yeah, I'll give it a try!

**Comment by chrswk** [comment]
Sorry for not creating a proper pull request (not really a Git/GitHub user). Here's a patch with the following changes:

- Make it work with latest i18next release (remove `compatibilityAPI`, use `changeLanguage`, use `{{name}}` in resources). Some of these changes break backwards compatibility. I don't know how you want to handle that. Maybe create a "legacy" bundle?
- Add `text` pseudo-attribute, similar to `html`, using `ko.utils`
- Add optional `options` parameter to `init` for passing custom options to i18next, similar to what marcosdiez proposed

https://gist.github.com/chrswk/7108b9d4720996f533db00c4d0f8c38e

**Comment by leMaik** [comment]
Creating a proper PR isn't _that_ hard. :wink: Just fork this project, create a new branch in your fork with the changes and push it. GitHub will automagically display a "Create Pull Request" button in your fork then.

Thank you anyway. :+1:

**Comment by Guymestef** [comment]
I've created the PR from the patch of @chrswk
